url: http://elliotjonathan94.github.io
name: Jay Elliot
description: Web Developer from INLS 161 at UNC Chapel Hill
email: elliotj@live.unc.edu
github: elliotjonathan94
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png